---
- name: That's So Raven  
  hosts: "{{ ansible_limit }}"
  gather_facts: no
  connection: 'local'
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ ontap_hostname }}"
      username: "{{ ontap_username }}"
      password: "{{ ontap_password }}"
      https: "{{ https }}"
      validate_certs: "{{ validate_certs }}"
  vars: 
    cert_common_name: "{{ ontap_hostname }}"
    cert_name_append: "--NetApp-CA-Signed--{{ ansible_date_time.iso8601_basic_short }}"
    cert_dir: "{{ playbook_dir}}/tmp/"
    cert_base_file_name: "{{ cert_dir }}{{ cert_common_name }}"
    private_key_file: "{{ cert_base_file_name }}.key"
    public_cert_file: "{{ cert_base_file_name }}.crt"
    intermediate_cert_file: "{{ cert_base_file_name }}-ca-bundle.crt"
  tasks:
  - name: Install the signed certificate on the ONTAP system
    netapp.ontap.na_ontap_security_certificates:
      common_name: "{{ cert_common_name }}"
      name: "{{ cert_common_name }}{{ cert_name_append }}"
      public_certificate: "{{ lookup('file', public_cert_file) }}"
      private_key: "{{ lookup('file', private_key_file) }}"
      svm: "{{ cert_svm }}"
      type: server
      intermediate_certificates: "{{ lookup('file', intermediate_cert_file) }}"
      expiry_time: "{{ expiry_time }}"

  - name: Get Serial Number from newly installed certificate
    netapp.ontap.na_ontap_rest_cli: 
      command: 'security/certificate'
      params: 
        type: server
        self-signed: "false"
        cert-name: "{{ cert_common_name }}{{ cert_name_append }}"
      verb: "GET"
    register: get_installed_cert
    
  - name: Set installed_cert fact
    ansible.builtin.set_fact:
      installed_cert: "{{ get_installed_cert['msg']['records'] | first }}"

  - name: Log of installed_cert
    ansible.builtin.debug:
      msg: "{{ installed_cert }}"

  - name: Activate the certificate
    netapp.ontap.na_ontap_rest_cli: 
      command: "security/ssl"
      params: 
        server-enabled: "true"
        vserver: "{{ cert_svm }}"
      body: 
        ca: "{{ installed_cert.ca }}"
        serial: "{{ installed_cert.serial }}"
        common-name: "{{ cert_common_name }}"
      verb: "PATCH"
    register: activate_cert

  - name: Log of activate_cert
    ansible.builtin.debug: 
      var: activate_cert

  # - name: Verify the newly installed cert is activated 
  
  # - name: Clean up the old cert(s) in ONTAP
  #   ansible.builtin.debug: 
  #     msg: "Placeholder"
