---
- name: Renewing expired vserver self-signed certificates 
  hosts: "{{ ansible_limit | default('localhost') }}"
  gather_facts: yes
  connection: 'local'
  collections:
    - netapp.ontap
  vars: 
    current_date_time: "{{ ansible_date_time.iso8601 }}"
    current_year: "{{ ansible_date_time.year }}"
    expiry_time:  P365DT # 1 year
    login: &login
      hostname: "{{ ontap_hostname }}"
      username: "{{ ontap_username }}"
      password: "{{ ontap_password }}"
      https: "{{ https }}"
      validate_certs: "{{ validate_certs }}"
  # https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_renew_a_Self-Signed_SSL_certificate_in_ONTAP_9_10_0_and_earlier
  tasks:
  - name: Gather vserver self-signed certificates that are expired
    include_tasks: tasks/ontap_get_cluster_info_rest.yml
    vars: 
      gather_subset: ['security/certificates']
      parameters: 
        type: server
        scope: svm
        expiry_time: "<{{ current_date_time }}"
      fields: ['uuid', 'name', 'svm', 'common_name','type','expiry_time']
      # gather_subset: ['svm/svms']
      # fields: ['*']
  - name: Create new self-signed certificates for each expired vserver cert 
    na_ontap_security_certificates: 
      <<: *login
      state: present
      name: "{{ item.name }}_{{ current_year }}"
      common_name: "{{ item.common_name }}_{{ current_year }}"
      type: server
      svm: "{{ item.svm.name }}"
      expiry_time: "{{ expiry_time }}"
    with_items: "{{ ontap_rest_info['security/certificates']['records'] }}"
  - name: Activate new certificates
    
  # - name: Delete expired certificates
  #   na_ontap_security_certificates: 
  #     <<: *login
  #     state: absent
  #     name: "{{ item.name }}"
  #     common_name: "{{ item.common_name }}"
  #     type: server
  #     svm: "{{ item.svm.name }}"
  #   with_items: "{{ ontap_rest_info['security/certificates']['records'] }}"