---
- name: Upgrading vserver self-signed certificates 
  hosts: "{{ ansible_limit | default('localhost') }}"
  gather_facts: no
  connection: 'local'
  collections:
    - netapp.ontap
  tasks:
  - name: Gather vserver self-signed certificates that are expired
    include_tasks: tasks/ontap_get_cluster_info_rest.yml
    vars: 
      gather_subset: ['security/certificates']
      parameters: 
        type: "server"
      fields: ['uuid', 'name']
      # gather_subset: ['svm/svms']
      # fields: ['*']
  - name: Check info
    debug: 
      var: ontap_rest_info
  - name: Renew them
    debug: 
      msg: "Check for expired certs"
  