- name: Check CPU and Disk utilization  
    (statistics show-periodic -preset sysstat_utilization -iterations 10 -interval 3)
  netapp.ontap.na_ontap_ssh_command:
    command: statistics show-periodic -preset sysstat_utilization -iterations 10 -interval 3
    privilege: adv
    accept_unknown_host_keys: true
  register: cpu_disk_check      

- name: Log of cpu_disk_check
  include_tasks: tasks/add_log.yml
  vars: 
    log: 
      statistics show-periodic -preset sysstat_utilization -iterations 10 -interval 3: "{{ cpu_disk_check.stdout }}"

- name: Add warning cpu_disk_check having anything over 50% in the stdout
  include_tasks: tasks/add_warning.yml
  vars: 
    warning:
      issue: "There are CPU and/ors disk utilizations over 50%."
      details: "{{ cpu_disk_check['stdout'] }}"
  when: cpu_disk_check | regex_findall('([5-9]\\d|[1-9]\\d{2,})(?=\\%)', multiline=True) | length > 0

