- name: Make sure key is set if there are no NTP servers
  ansible.builtin.set_fact: 
    cluster_info: "{{ cluster_info | combine({'ntp_servers': []}) }}"
  when: cluster_info.ntp_servers is undefined

- name: Fail playbook if there are not at least 3 NTP Servers
  include_tasks: tasks/add_failure.yml
  vars: 
    failure: 
      issue: "There must be at least three NTP servers per NetApp best practices 
              but there are currently {{ cluster_info.ntp_servers | length }}"
      details: "{{ cluster_info.ntp_servers }}"
  when: cluster_info.ntp_servers | length < 3

- name: Set cluster_dates  
  ansible.builtin.set_fact: 
    cluster_dates: "{{ cluster_nodes | map(attribute='date', default='') | list }}"

- name: Log cluster_dates
  include_tasks: tasks/add_log.yml
  vars: 
    log: 
      cluster_dates: "{{ cluster_dates }}"

- name: Add warning if there is any variation among node timestamps 
  include_tasks: tasks/add_warning.yml
  vars: 
    warning: 
      issue: "Dates and timezones should ideally match on all nodes"
      details: "{{ cluster_dates }}"
  when: cluster_dates | unique | length > 1
