- name: Make sure key is set if there are no NTP servers
  ansible.builtin.set_fact: 
    cluster_info: "{{ cluster_info | combine({'ntp_servers': []}) }}"
  when: cluster_info.ntp_servers is undefined

- name: Fail playbook if there are not at least 3 NTP Servers
  include_tasks: tasks/add_failure.yml
  vars: 
    failure: 
      issue: "There must be at least three NTP servers per NetApp best practices 
              but there are currently {{ cluster_info.ntp_servers | length }}"
      details: "{{ cluster_info.ntp_servers }}"
  when: cluster_info.ntp_servers | length < 3

- name: Show Datetime (`cluster date show`) 
  netapp.ontap.na_ontap_rest_cli: 
    command: 'cluster/date'
    params: 
      fields: "node,date,timezone"
    verb: "GET"
  register: verify_datetime
  
- name: Set cluster_datetime 
  ansible.builtin.set_fact: 
    cluster_datetime: "{{ verify_datetime.msg.records }}"

- name: Log of Cluster Datetime
  include_tasks: tasks/add_log.yml
  vars: 
    log: 
      cluster date show: "{{ cluster_datetime | dicts_to_table }}"

- name: Set cluster_dates_compare and cluster_timezone_compare  
  ansible.builtin.set_fact: 
    cluster_timezone_compare: "{{ cluster_datetime | map(attribute='timezone', default='') | list }}"
    cluster_dates_compare: "{{ cluster_datetime | map(attribute='date', default='') | list }}"

- name: Add warning if there is any variation among node timestamps 
  include_tasks: tasks/add_warning.yml
  vars: 
    warning: 
      issue: "Dates and timezones should ideally match on all nodes"
      details: "{{ cluster_datetime | dicts_to_table }}"
  when: cluster_dates_compare | unique | length > 1 
        or cluster_timezone_compare | unique | length > 1 
