- name: Find any DP SnampMirrors (`snapmirror list-destinations`)
  netapp.ontap.na_ontap_rest_cli: 
    command: 'snapmirror/list-destinations'
    params: 
      type: "DP"
    verb: "GET"
  register: verify_snapmirror_dp_destinations

- name: Log of verify_snapmirror_dp_destinations
  include_tasks: tasks/add_log.yml
  vars: 
    log: 
      DP Snapmirrors: "{{ verify_snapmirror_dp_destinations.msg.records | dicts_to_table }}"
  when: verify_snapmirror_dp_destinations.msg.num_records > 0
