- name: Verify failover status (`storage failover show`)  
  netapp.ontap.na_ontap_rest_cli: 
    command: 'storage/failover'
    params: 
      fields: "node,partner-name,enabled,possible,state-description"
    verb: "GET"
  register: get_failover_status

- name: Set failover_status 
  ansible.builtin.set_fact:
    failover_status: "{{ get_failover_status.msg.records }}"

- name: Log of verify_failover_status
  include_tasks: tasks/add_log.yml
  vars: 
    log: 
      storage failover show: "{{ failover_status | dicts_to_table }}"

- name: Check for any nodes where failover isn't possible
  ansible.builtin.set_fact: 
    failover_not_possible: "{{ failover_status | selectattr('possible','false') | list }}"

- name: Enable failover for any nodes where it's disabled on 4+ node clusters (later, we will ensure two node clusters are in HA mode, which automatically turns on storage failover)  
  block: 

  - name: Log of failover_not_possible
    include_tasks: tasks/add_log.yml
    vars: 
      log: 
        Failover Not Possible: "{{ failover_not_possible | dicts_to_table }}"

  - name: Enable storage failover (`netapp.ontap.na_ontap_storage_failover`)
    netapp.ontap.na_ontap_storage_failover:
      state: present
      node_name: "{{ failover_not_possible | map(attribute='node') | join(',') }}"
    register: enable_failover

  - name: Log of enable_failover
    include_tasks: tasks/add_log.yml
    vars: 
      log: 
        netapp.ontap.na_ontap_storage_failover: "{{ enable_failover }}"

  - name: Add failure if failover was not enabled on all nodes
    include_tasks: tasks/add_failure.yml
    args:
      apply:
        tags: health
    vars: 
      failure: 
        issue: "Failover was not sucessfully enabled on all nodes"
        details: "{{ failover_not_possible }}"
    when: enable_failover.failed == true or enable_failover.msg.num_records != failover_not_possible | length 

  when: failover_not_possible | length > 0 and cluster_node_count | int > 2
