- name: Check for any critical health alerts (`health alert show`)
  netapp.ontap.na_ontap_rest_cli: 
    command: 'system/health/alert'
    verb: "GET"
  register: get_health_alerts

- name: Log of get_health_alerts
  include_tasks: tasks/add_log.yml
  vars: 
    log: 
      health alert show: "{{ get_health_alerts.msg.records }}"

- name: Add failure if there are critical health alerts
  include_tasks: tasks/add_failure.yml
  vars: 
    failure: 
      issue: "There are critical health alerts" 
      details: "{{ get_health_alerts.msg.records | dicts_to_table }}"
  when: get_health_alerts.msg.num_records > 0

- name: Check subsystem health (`health subsystem show`)
  netapp.ontap.na_ontap_rest_cli: 
    command: 'system/health/subsystem'
    params: 
      fields: "health"
    verb: "GET"
  register: get_health_subsystem

- name: Set health_subsystem
  ansible.builtin.set_fact:
    health_subsystem: "{{ get_health_subsystem.msg.records }}"
    health_subsystem_log: "{{ get_health_subsystem.msg.records | dicts_to_table }}"

- name: Log of health_subsystem
  include_tasks: tasks/add_log.yml
  vars: 
    log: 
      health subsystem show: "{{ health_subsystem_log }}"

- name: Add failure if there are subsystems degraded 
  include_tasks: tasks/add_failure.yml
  vars: 
    failure: 
      issue: "There are subsystems that are not in a healthy state"
      details: "{{ health_subsystem_log }}"
  when: health_subsystem|selectattr('health','!=','ok')|list|length > 0
