- name: Get uptime (`system node show -fields uptime`) 
  netapp.ontap.na_ontap_rest_cli: 
    command: 'system/node'
    params: 
      fields: "model,uptime"
    verb: "GET"
  register: verify_uptime

- name: Get current ONTAP Version
  netapp.ontap.na_ontap_rest_cli: 
    command: 'system/image'
    params: 
      iscurrent: "true"
      fields: "image,node,version"
    verb: "GET"
  register: verify_ontap_version

- name: Set uptime_and_os var
  ansible.builtin.set_fact: 
    uptime_and_os: "{{ verify_ontap_version.msg.records | community.general.lists_mergeby(verify_uptime.msg.records, 'node') }}"
