- name: Check for any critical health alerts (`health alert show`)
  netapp.ontap.na_ontap_rest_cli: 
    hostname: "{{ ontap_hostname }}"
    username: "{{ ontap_username }}"
    password: "{{ ontap_password }}"
    https: "{{ https }}"
    validate_certs: "{{ validate_certs }}"
    command: 'system/health/alert'
    verb: "GET"
  register: verify_health_alerts
    
- name: Add failure if there are critical health alerts
  include_tasks: tasks/add_failure.yml
  vars: 
    failure: 
      issue: "There are critical health alerts" 
      details: "{{ verify_health_alerts.msg.records }}"
  when: verify_health_alerts.msg.num_records > 0

- name: Check subsystem health (`health subsystem show`)
  netapp.ontap.na_ontap_rest_cli: 
    # hostname: "{{ ontap_hostname }}"
    # username: "{{ ontap_username }}"
    # password: "{{ ontap_password }}"
    # https: "{{ https }}"
    # validate_certs: "{{ validate_certs }}"
    command: 'system/health/subsystem'
    params: 
      fields: "health"
    verb: "GET"
  register: verify_health_subsystems

- name: Log of verify_health_subsystems
  include_tasks: tasks/add_log.yml
  vars: 
    log: 
      health_subsystems: "{{ verify_health_subsystems }}"

- name: Add failure if there are subsystems degraded 
  include_tasks: tasks/add_failure.yml
  vars: 
    failure: 
      issue: "There are subsystems that are not in a healthy state"
      details: "{{ verify_health_subsystems.msg.records }}"
  when: verify_health_subsystems.msg.records|selectattr('health','!=','ok')|list|length > 0
