- name: |
    Check to see if the package has already been uploaded
    (`system node image show`)
  netapp.ontap.na_ontap_rest_cli: 
    command: 'system/node/image'
    params: 
      fields: "image,node,version"
    verb: "GET"
  register: node_image_show

- name: Set current_node_images
  ansible.builtin.set_fact: 
    current_node_images: "{{ node_image_show.msg.records }}"

- name: Build list of versions per node
  ansible.builtin.set_fact: 
    nodes_with_new_package: "{{ current_node_images | selectattr('version', 'equalto', ontap_package_version) }}" 
    
- name: "Build list of nodes without {{ ontap_package_version }}"
  ansible.builtin.set_fact: 
    nodes_need_new_image: "{{ nodes_need_new_image | default([]) + [item] }}"
  loop: "{{ nodes_list }}"
  loop_control: 
    label: "{{ item.name }} {{ item.version.full }}"
  when: item not in nodes_with_new_package | map(attribute="node")