- name: |
    Get all enabled LIFs with the home node set to <node>
    (`netapp.ontap.na_ontap_restit network/ip/interfaces`)
  netapp.ontap.na_ontap_restit:
    api: network/ip/interfaces
    query:
      location.home_node.name: "{{ node }}"
      fields: "*"
      enabled: true
  register: get_node_lifs

- name: Set node_lifs fact
  ansible.builtin.set_fact: 
    node_lifs: "{{ get_node_lifs.response.records }}"

- name: Log node_lifs
  ansible.builtin.debug: 
    var: node_lifs | pprint

- name: Log node_lifs
  ansible.builtin.debug: 
    msg: |
     LIF   State  Current   Home 
     {% for l in node_lifs %}
     {{ l.name +'  '+l.state|upper+'  '+l.location.node.name +':'+l.location.port.name+'  '+l.location.home_node.name+':'+l.location.home_port.name}}
     {% endfor %} 
