---
- name: "Determine where in the upgrade process each cluster is"
  hosts: "{{ clusters | default('localhost') }}"
  gather_facts: no
  connection: 'local'
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ ontap_hostname }}"
      username: "{{ ontap_username }}"
      password: "{{ ontap_password }}"
      https: "{{ https }}"
      validate_certs: "{{ validate_certs }}"
  vars_files: 
    - http_server.yml
  vars: 
    ontap_image: 9101P15_q_image.tgz
    ontap_package_version: 9.10.1P15
    ontap_package_url: "{{ http_server_url }}/{{ ontap_image }}"
    upgrade_status: not_started
  pre_tasks: 
  - include_tasks: tasks/check_package_url.yml
  tasks:

  - name: Get failover status (`storage failover show`)  
    netapp.ontap.na_ontap_rest_cli: 
      command: 'storage/failover'
      params: 
        fields: "node,partner-name,partner-reason,enabled,possible,state-description"
      verb: "GET"
    register: get_failover_status

  - name: Set failover_status
    ansible.builtin.set_fact: 
      failover_status: get_failover_status['msg']['records'] 

  - name: Get versions currently on each node (`netapp.ontap.na_ontap_rest_info`)
    include_tasks: tasks/rest_info.yml
    vars: 
      gather_subset:
      - cluster/nodes
      fields: 
        - "ha,state,version"

  - name: Check for 'MAINT=<n>h Starting' autosupports within the last 4 hours
    netapp.ontap.na_ontap_rest_cli: 
      command: 'system/node/autosupport/history'
      params: 
        fields: "subject,trigger,error,last-update,status"
        subject: "*ALL:MAINT=*h Starting*"
        last-update: ">120m"
      verb: "GET"
    register: get_maint_autosupports

  - name: Set maint_autosupports
    ansible.builtin.set_fact: 
      maint_autosupports: "{{ get_maint_autosupports['msg']['records'] }}"

      # - name: Get package list 
  #   netapp.ontap.na_ontap_rest_cli
